### ISSUE TITLE
can't seem to use the keymap

### ISSUE THREAD

**Issue by vendethiel** [ngn/vim-apl#5]
Hi,

Your plugin works nicely, but I've had issues trying to use the keymap.

1. my vim is compiled with `+keymap +langmap`
2. `:scriptnames` shows the keymap
3. I tried to use `Ctrl-Shift-6` to switch keymap, but that hasn't helped
4. I change keymap with `:setf apl` and then `:set kmp=apl`

Trying to enter either ``` `w ``` or C-u ``` `w ``` just prints a `w`.

**Comment by ngn** [comment]
To be honest, I haven't got a clue about what might be wrong.  A few things to double check:
Does your terminal (or the GUI, if you're using gvim) use a font that supports APL characters?  What do you see if you type `<C-v>u2375` in insert mode?  That's a Unicode escape for omega.  Do `w` and `⍵` look sufficiently distinguishable?  Do you see the mappings when you type `:lmap`?  Are you by any chance using a national keyboard layout that treats backquote as a [dead key](https://en.wikipedia.org/wiki/Dead_key)?

**Comment by vendethiel** [comment]
> Are you by any chance using a national keyboard layout that treats backquote as a dead key?

That seems to be it! As a frenchie, I do indeed use backquote. I guess I need to configure some other prefix key, then? I tried with `-`, but that didn't work.

**Comment by vendethiel** [comment]
Seems like multi-characters :lmap don't work anyway. mmh...

**Comment by vendethiel** [comment]
Oh god. I finally got it. Since I'm in a terminal, I got annoyed about stuff waiting (like `O`) so I set the timeout to 10... whoops... Works very well with 100...
