### ISSUE TITLE
Tradfns not being indented properly

### ISSUE THREAD

**Issue by kritixilithos** [ngn/vim-apl#9]
Here is a sample of APL code that has been `gg=G`ed.

```APL
∇ res←rand len
res←,0.5-⍨10÷⍨len?10
∇
```

As seen, the middle line is not indented when it should be indented.

**Comment by ngn** [comment]
The trouble is, `∇` is ambiguous - it means _recur_ in dfns.
So I made it assume it's a tradfn header/footer only when `∇` is in the first column.
Note that Dyalog indents tradfn bodies with 2 spaces, even if control structures use 4.
My advice: use only dfns :)
